# Nombre del proyecto que aparecerá en el encabezado del reporte
serenity.project.name=Automatizacion DemoQA Screenplay

# Paquete raíz donde Serenity buscará las clases con la anotación @Before / StepDefinitions
serenity.test.root=stepdefinitions

# Configuración de captura de pantalla
serenity.take.screenshots=FOR_EACH_ACTION